"""A junk mesh payload must fail loudly, not be stored and called a success.

Found while checking why set_mesh's error message was unhelpful: for three of
the five stand-in tokens observed in the 2026-08 sweeps there was no error at
all. ``base64.b64decode`` (no ``validate=``) accepts any string whose length and
alphabet happen to work out:

    'exported'            -> b'{\\x1ah\\xae\\xd7\\x9d'   6 bytes, ACCEPTED
    'base64_mesh_data=='  -> 10 bytes,                    ACCEPTED
    'SGVsbG8gd29ybGQ='    -> b'Hello world',              ACCEPTED

Those bytes were written to mesh.su2 and ``set_mesh`` returned {"mesh_path":...}
-- success. The caller had no reason to doubt the mesh was in place, so the
failure surfaced later and somewhere else, as SU2 complaining about a mesh that
had apparently been set moments earlier. Silent corruption is worse than a bad
error message: no error message at all is reachable from it.

The check is the SU2 native format's own requirement (a .su2 file declares
NDIME= in its header -- a real 88 MB export here starts "NDIME= 3"), not a size
threshold, and it applies only to the format we can identify.
"""

import base64

import pytest

from su2_mcp.session_manager import decode_mesh

# Shape of a real .su2 header, from integration_tests/output/d150_cfd.su2.
REAL_MESH = b"NDIME= 3\nNELEM= 1836397\n10 40955 79425 136981 178603 0\n"
REAL_B64 = base64.b64encode(REAL_MESH).decode()


class TestObservedJunkIsRejected:
    @pytest.mark.parametrize("token", [
        "exported",             # decoded to 6 bytes and was STORED
        "base64_mesh_data==",   # decoded to 10 bytes and was STORED
        "SGVsbG8gd29ybGQ=",     # "Hello world" -- decoded and was STORED
    ])
    def test_decodable_but_not_a_mesh(self, token):
        with pytest.raises(ValueError, match="not an SU2 mesh"):
            decode_mesh(token, "mesh.su2")

    def test_error_says_the_mesh_was_not_stored(self):
        with pytest.raises(ValueError, match="NOT stored"):
            decode_mesh("exported", "mesh.su2")

    def test_error_names_the_argument_and_the_requirement(self):
        with pytest.raises(ValueError) as exc:
            decode_mesh("exported", "mesh.su2")
        assert "mesh_base64" in str(exc.value)
        assert "NDIME=" in str(exc.value)

    def test_error_shows_what_arrived(self):
        """So the caller can see it sent a token, not a mesh."""
        with pytest.raises(ValueError) as exc:
            decode_mesh(base64.b64encode(b"/tmp/mesh.su2").decode(), "mesh.su2")
        assert "/tmp/mesh.su2" in str(exc.value)


class TestRealMeshesPassThrough:
    def test_real_su2_header_accepted(self):
        assert decode_mesh(REAL_B64, "mesh.su2") == REAL_MESH

    def test_large_mesh_accepted(self):
        big = REAL_MESH + b"1 2 3 4 5 6\n" * 5000
        assert decode_mesh(base64.b64encode(big).decode(), "mesh.su2") == big

    def test_leading_comment_before_ndime_accepted(self):
        body = b"%% generated by tigl\nNDIME= 3\nNELEM= 4\n"
        assert decode_mesh(base64.b64encode(body).decode(), "mesh.su2") == body

    def test_ndime_is_sought_case_sensitively_in_a_window(self):
        """A mesh whose NDIME sits past the window would be a false reject, so
        keep the window generous enough for real preambles."""
        body = b"%" * 400 + b"\nNDIME= 3\n"
        assert decode_mesh(base64.b64encode(body).decode(), "mesh.su2") == body


class TestFormatsWeCannotIdentifyAreNotGuessedAt:
    """Validating only the format we know beats inventing a minimum size."""

    def test_cgns_passes_through(self):
        blob = b"\x89HDF\r\n\x1a\n" + b"\x00" * 64
        assert decode_mesh(base64.b64encode(blob).decode(), "mesh.cgns") == blob

    def test_non_su2_extension_not_content_checked(self):
        assert decode_mesh("exported", "mesh.cgns") == base64.b64decode("exported")


class TestUndecodableStillRaises:
    @pytest.mark.parametrize("token", ["<MESH_BASE64_FROM_GEOMETRY_STAGE>", "mesh.su2"])
    def test_bad_base64_rejected(self, token):
        with pytest.raises(Exception):
            decode_mesh(token, "mesh.su2")


class TestBothEntryPointsAreGuarded:
    """create_session(initial_mesh=...) decodes separately from update_mesh, and
    the framework guard once missed exactly that second door."""

    def test_set_mesh_reports_the_failure(self, tmp_path, monkeypatch):
        from su2_mcp.tools import config_tools

        class _Rec:
            config_path = tmp_path / "c.cfg"
            workdir = tmp_path

        from su2_mcp.session_manager import SessionManager

        mgr = SessionManager()
        monkeypatch.setattr(mgr, "require", lambda sid: _Rec())
        monkeypatch.setattr(config_tools, "SESSION_MANAGER", mgr)
        _Rec.config_path.write_text("% empty\n")

        out = config_tools.set_mesh("s", "exported")
        assert "error" in out
        assert not (tmp_path / "mesh.su2").exists(), "junk must not be written"

    def test_message_does_not_misdescribe_its_own_cause(self):
        """`'exported'` IS valid base64 -- it just is not a mesh. Reporting it as
        "not decodable base64" while quoting a decoded byte count contradicts
        itself, and that is the defect class this whole pass removes. Live text
        before the fix:

            mesh_base64 is not decodable base64 (mesh_base64 decoded to 6 bytes
            that are not an SU2 mesh: ...)

        The earlier test here missed it by mocking the session manager with
        `validate=True`, which raises binascii.Error and never reaches the
        decode_mesh branch.
        """
        from su2_mcp.session_manager import SessionManager
        from su2_mcp.tools import config_tools

        mgr = SessionManager()
        sid = mgr.create_session().session_id
        prev = config_tools.SESSION_MANAGER
        config_tools.SESSION_MANAGER = mgr
        try:
            msg = config_tools.set_mesh(sid, "exported")["error"]["message"]
        finally:
            config_tools.SESSION_MANAGER = prev

        assert "not an SU2 mesh" in msg
        for contradiction in ("not valid base64", "not decodable base64",
                              "Invalid base64-encoded", "Incorrect padding"):
            assert contradiction not in msg, f"message contradicts itself: {msg}"

    def test_genuinely_bad_base64_still_says_base64(self):
        """The other branch must keep its own, correct wording."""
        from su2_mcp.session_manager import SessionManager
        from su2_mcp.tools import config_tools

        mgr = SessionManager()
        sid = mgr.create_session().session_id
        prev = config_tools.SESSION_MANAGER
        config_tools.SESSION_MANAGER = mgr
        try:
            msg = config_tools.set_mesh(sid, "<MESH_BASE64_HERE>")["error"]["message"]
        finally:
            config_tools.SESSION_MANAGER = prev

        assert "not valid base64" in msg

    def test_create_session_rejects_junk_initial_mesh(self):
        from su2_mcp.session_manager import SessionManager

        with pytest.raises(ValueError, match="not an SU2 mesh"):
            SessionManager().create_session(initial_mesh="exported")
